/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.4.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QAction>
#include <QtWidgets/QApplication>
#include <QtWidgets/QButtonGroup>
#include <QtWidgets/QDoubleSpinBox>
#include <QtWidgets/QGroupBox>
#include <QtWidgets/QHeaderView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenu>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QSpinBox>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QToolBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QAction *actionLoad_traning_sample;
    QAction *actionLoad_test_sample;
    QAction *actionSave_network_configuration;
    QAction *actionLoad_network_configuration;
    QWidget *centralWidget;
    QLabel *label;
    QSpinBox *spinBox;
    QSpinBox *spinBox_2;
    QLabel *label_3;
    QLabel *label_4;
    QLabel *max_weight_nn;
    QLabel *min_weight_nn;
    QLineEdit *lineEdit;
    QLineEdit *lineEdit_2;
    QLineEdit *lineEdit_3;
    QLineEdit *lineEdit_4;
    QLabel *max_weight_nn_2;
    QLabel *min_weight_nn_2;
    QGroupBox *groupBox;
    QLabel *label_2;
    QGroupBox *groupBox_2;
    QGroupBox *groupBox_3;
    QLineEdit *lineEdit_5;
    QLabel *label_5;
    QLabel *max_weight_nn_3;
    QLabel *min_weight_nn_3;
    QLineEdit *lineEdit_6;
    QLineEdit *lineEdit_7;
    QGroupBox *groupBox_4;
    QLabel *min_weight_nn_4;
    QLineEdit *lineEdit_8;
    QLabel *label_6;
    QLabel *label_7;
    QLabel *max_weight_nn_5;
    QSpinBox *spinBox_4;
    QLineEdit *lineEdit_10;
    QGroupBox *groupBox_6;
    QLabel *max_weight_nn_6;
    QLabel *label_9;
    QLineEdit *lineEdit_12;
    QLabel *min_weight_nn_6;
    QLabel *min_weight_nn_7;
    QLabel *label_8;
    QLineEdit *lineEdit_11;
    QGroupBox *groupBox_7;
    QLineEdit *lineEdit_9;
    QSpinBox *spinBox_5;
    QGroupBox *groupBox_5;
    QLabel *min_weight_nn_5;
    QLabel *label_10;
    QLabel *label_11;
    QLineEdit *lineEdit_13;
    QLabel *max_weight_nn_7;
    QLineEdit *lineEdit_14;
    QLabel *max_weight_nn_8;
    QPushButton *pushButton;
    QSpinBox *spinBox_3;
    QTextEdit *textEdit;
    QLabel *label_12;
    QLineEdit *lineEdit_15;
    QLabel *label_13;
    QSpinBox *spinBox_6;
    QLabel *label_14;
    QLabel *label_15;
    QDoubleSpinBox *doubleSpinBox;
    QPushButton *pushButton_2;
    QDoubleSpinBox *doubleSpinBox_2;
    QLabel *label_16;
    QLabel *label_17;
    QLabel *label_18;
    QLineEdit *lineEdit_16;
    QMenuBar *menuBar;
    QMenu *menuFile;
    QToolBar *mainToolBar;
    QStatusBar *statusBar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QStringLiteral("MainWindow"));
        MainWindow->resize(721, 636);
        QSizePolicy sizePolicy(QSizePolicy::Fixed, QSizePolicy::Fixed);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(MainWindow->sizePolicy().hasHeightForWidth());
        MainWindow->setSizePolicy(sizePolicy);
        MainWindow->setMinimumSize(QSize(721, 636));
        MainWindow->setMaximumSize(QSize(721, 636));
        QFont font;
        font.setStyleStrategy(QFont::PreferAntialias);
        MainWindow->setFont(font);
        actionLoad_traning_sample = new QAction(MainWindow);
        actionLoad_traning_sample->setObjectName(QStringLiteral("actionLoad_traning_sample"));
        actionLoad_test_sample = new QAction(MainWindow);
        actionLoad_test_sample->setObjectName(QStringLiteral("actionLoad_test_sample"));
        actionSave_network_configuration = new QAction(MainWindow);
        actionSave_network_configuration->setObjectName(QStringLiteral("actionSave_network_configuration"));
        actionLoad_network_configuration = new QAction(MainWindow);
        actionLoad_network_configuration->setObjectName(QStringLiteral("actionLoad_network_configuration"));
        centralWidget = new QWidget(MainWindow);
        centralWidget->setObjectName(QStringLiteral("centralWidget"));
        label = new QLabel(centralWidget);
        label->setObjectName(QStringLiteral("label"));
        label->setGeometry(QRect(120, 30, 56, 56));
        label->setFrameShape(QFrame::Box);
        label->setFrameShadow(QFrame::Plain);
        label->setScaledContents(false);
        spinBox = new QSpinBox(centralWidget);
        spinBox->setObjectName(QStringLiteral("spinBox"));
        spinBox->setGeometry(QRect(80, 100, 101, 22));
        spinBox->setMaximum(99999999);
        spinBox_2 = new QSpinBox(centralWidget);
        spinBox_2->setObjectName(QStringLiteral("spinBox_2"));
        spinBox_2->setGeometry(QRect(320, 110, 51, 22));
        spinBox_2->setMaximum(999999);
        label_3 = new QLabel(centralWidget);
        label_3->setObjectName(QStringLiteral("label_3"));
        label_3->setGeometry(QRect(310, 30, 56, 56));
        label_3->setFrameShape(QFrame::Box);
        label_3->setFrameShadow(QFrame::Plain);
        label_3->setScaledContents(false);
        label_4 = new QLabel(centralWidget);
        label_4->setObjectName(QStringLiteral("label_4"));
        label_4->setGeometry(QRect(320, 90, 51, 22));
        label_4->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        max_weight_nn = new QLabel(centralWidget);
        max_weight_nn->setObjectName(QStringLiteral("max_weight_nn"));
        max_weight_nn->setGeometry(QRect(210, 30, 47, 16));
        min_weight_nn = new QLabel(centralWidget);
        min_weight_nn->setObjectName(QStringLiteral("min_weight_nn"));
        min_weight_nn->setGeometry(QRect(210, 70, 47, 16));
        lineEdit = new QLineEdit(centralWidget);
        lineEdit->setObjectName(QStringLiteral("lineEdit"));
        lineEdit->setGeometry(QRect(210, 50, 91, 20));
        lineEdit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit->setReadOnly(true);
        lineEdit_2 = new QLineEdit(centralWidget);
        lineEdit_2->setObjectName(QStringLiteral("lineEdit_2"));
        lineEdit_2->setGeometry(QRect(210, 90, 91, 20));
        lineEdit_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_2->setReadOnly(true);
        lineEdit_3 = new QLineEdit(centralWidget);
        lineEdit_3->setObjectName(QStringLiteral("lineEdit_3"));
        lineEdit_3->setGeometry(QRect(50, 60, 60, 20));
        lineEdit_3->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_3->setReadOnly(true);
        lineEdit_4 = new QLineEdit(centralWidget);
        lineEdit_4->setObjectName(QStringLiteral("lineEdit_4"));
        lineEdit_4->setGeometry(QRect(50, 40, 60, 20));
        lineEdit_4->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_4->setReadOnly(true);
        max_weight_nn_2 = new QLabel(centralWidget);
        max_weight_nn_2->setObjectName(QStringLiteral("max_weight_nn_2"));
        max_weight_nn_2->setGeometry(QRect(20, 40, 47, 16));
        min_weight_nn_2 = new QLabel(centralWidget);
        min_weight_nn_2->setObjectName(QStringLiteral("min_weight_nn_2"));
        min_weight_nn_2->setGeometry(QRect(20, 60, 47, 16));
        groupBox = new QGroupBox(centralWidget);
        groupBox->setObjectName(QStringLiteral("groupBox"));
        groupBox->setGeometry(QRect(10, 9, 181, 131));
        label_2 = new QLabel(groupBox);
        label_2->setObjectName(QStringLiteral("label_2"));
        label_2->setGeometry(QRect(10, 90, 61, 22));
        label_2->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        groupBox_2 = new QGroupBox(centralWidget);
        groupBox_2->setObjectName(QStringLiteral("groupBox_2"));
        groupBox_2->setGeometry(QRect(200, 10, 181, 131));
        groupBox_3 = new QGroupBox(centralWidget);
        groupBox_3->setObjectName(QStringLiteral("groupBox_3"));
        groupBox_3->setGeometry(QRect(390, 10, 181, 131));
        lineEdit_5 = new QLineEdit(centralWidget);
        lineEdit_5->setObjectName(QStringLiteral("lineEdit_5"));
        lineEdit_5->setGeometry(QRect(400, 50, 91, 20));
        lineEdit_5->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_5->setReadOnly(true);
        label_5 = new QLabel(centralWidget);
        label_5->setObjectName(QStringLiteral("label_5"));
        label_5->setGeometry(QRect(500, 30, 56, 56));
        label_5->setFrameShape(QFrame::Box);
        label_5->setFrameShadow(QFrame::Plain);
        label_5->setScaledContents(false);
        max_weight_nn_3 = new QLabel(centralWidget);
        max_weight_nn_3->setObjectName(QStringLiteral("max_weight_nn_3"));
        max_weight_nn_3->setGeometry(QRect(400, 30, 47, 16));
        min_weight_nn_3 = new QLabel(centralWidget);
        min_weight_nn_3->setObjectName(QStringLiteral("min_weight_nn_3"));
        min_weight_nn_3->setGeometry(QRect(400, 70, 47, 16));
        lineEdit_6 = new QLineEdit(centralWidget);
        lineEdit_6->setObjectName(QStringLiteral("lineEdit_6"));
        lineEdit_6->setGeometry(QRect(399, 90, 91, 20));
        lineEdit_6->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_6->setReadOnly(true);
        lineEdit_7 = new QLineEdit(centralWidget);
        lineEdit_7->setObjectName(QStringLiteral("lineEdit_7"));
        lineEdit_7->setGeometry(QRect(400, 240, 91, 20));
        lineEdit_7->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_7->setReadOnly(true);
        groupBox_4 = new QGroupBox(centralWidget);
        groupBox_4->setObjectName(QStringLiteral("groupBox_4"));
        groupBox_4->setGeometry(QRect(390, 160, 181, 131));
        min_weight_nn_4 = new QLabel(centralWidget);
        min_weight_nn_4->setObjectName(QStringLiteral("min_weight_nn_4"));
        min_weight_nn_4->setGeometry(QRect(210, 220, 47, 16));
        lineEdit_8 = new QLineEdit(centralWidget);
        lineEdit_8->setObjectName(QStringLiteral("lineEdit_8"));
        lineEdit_8->setGeometry(QRect(209, 240, 91, 20));
        lineEdit_8->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_8->setReadOnly(true);
        label_6 = new QLabel(centralWidget);
        label_6->setObjectName(QStringLiteral("label_6"));
        label_6->setGeometry(QRect(310, 180, 56, 56));
        label_6->setFrameShape(QFrame::Box);
        label_6->setFrameShadow(QFrame::Plain);
        label_6->setScaledContents(false);
        label_7 = new QLabel(centralWidget);
        label_7->setObjectName(QStringLiteral("label_7"));
        label_7->setGeometry(QRect(320, 240, 51, 22));
        label_7->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        max_weight_nn_5 = new QLabel(centralWidget);
        max_weight_nn_5->setObjectName(QStringLiteral("max_weight_nn_5"));
        max_weight_nn_5->setGeometry(QRect(400, 180, 47, 16));
        spinBox_4 = new QSpinBox(centralWidget);
        spinBox_4->setObjectName(QStringLiteral("spinBox_4"));
        spinBox_4->setGeometry(QRect(320, 260, 51, 22));
        spinBox_4->setMaximum(999999);
        lineEdit_10 = new QLineEdit(centralWidget);
        lineEdit_10->setObjectName(QStringLiteral("lineEdit_10"));
        lineEdit_10->setGeometry(QRect(400, 200, 91, 20));
        lineEdit_10->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_10->setReadOnly(true);
        groupBox_6 = new QGroupBox(centralWidget);
        groupBox_6->setObjectName(QStringLiteral("groupBox_6"));
        groupBox_6->setGeometry(QRect(200, 160, 181, 131));
        max_weight_nn_6 = new QLabel(centralWidget);
        max_weight_nn_6->setObjectName(QStringLiteral("max_weight_nn_6"));
        max_weight_nn_6->setGeometry(QRect(210, 180, 47, 16));
        label_9 = new QLabel(centralWidget);
        label_9->setObjectName(QStringLiteral("label_9"));
        label_9->setGeometry(QRect(500, 180, 56, 56));
        label_9->setFrameShape(QFrame::Box);
        label_9->setFrameShadow(QFrame::Plain);
        label_9->setScaledContents(false);
        lineEdit_12 = new QLineEdit(centralWidget);
        lineEdit_12->setObjectName(QStringLiteral("lineEdit_12"));
        lineEdit_12->setGeometry(QRect(210, 200, 91, 20));
        lineEdit_12->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_12->setReadOnly(true);
        min_weight_nn_6 = new QLabel(centralWidget);
        min_weight_nn_6->setObjectName(QStringLiteral("min_weight_nn_6"));
        min_weight_nn_6->setGeometry(QRect(400, 220, 47, 16));
        min_weight_nn_7 = new QLabel(centralWidget);
        min_weight_nn_7->setObjectName(QStringLiteral("min_weight_nn_7"));
        min_weight_nn_7->setGeometry(QRect(400, 370, 47, 16));
        label_8 = new QLabel(centralWidget);
        label_8->setObjectName(QStringLiteral("label_8"));
        label_8->setGeometry(QRect(310, 330, 56, 56));
        label_8->setFrameShape(QFrame::Box);
        label_8->setFrameShadow(QFrame::Plain);
        label_8->setScaledContents(false);
        lineEdit_11 = new QLineEdit(centralWidget);
        lineEdit_11->setObjectName(QStringLiteral("lineEdit_11"));
        lineEdit_11->setGeometry(QRect(400, 350, 91, 20));
        lineEdit_11->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_11->setReadOnly(true);
        groupBox_7 = new QGroupBox(centralWidget);
        groupBox_7->setObjectName(QStringLiteral("groupBox_7"));
        groupBox_7->setGeometry(QRect(200, 310, 181, 131));
        lineEdit_9 = new QLineEdit(centralWidget);
        lineEdit_9->setObjectName(QStringLiteral("lineEdit_9"));
        lineEdit_9->setGeometry(QRect(400, 390, 91, 20));
        lineEdit_9->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_9->setReadOnly(true);
        spinBox_5 = new QSpinBox(centralWidget);
        spinBox_5->setObjectName(QStringLiteral("spinBox_5"));
        spinBox_5->setGeometry(QRect(320, 410, 51, 22));
        spinBox_5->setMaximum(999999);
        groupBox_5 = new QGroupBox(centralWidget);
        groupBox_5->setObjectName(QStringLiteral("groupBox_5"));
        groupBox_5->setGeometry(QRect(390, 310, 181, 131));
        min_weight_nn_5 = new QLabel(centralWidget);
        min_weight_nn_5->setObjectName(QStringLiteral("min_weight_nn_5"));
        min_weight_nn_5->setGeometry(QRect(210, 370, 47, 16));
        label_10 = new QLabel(centralWidget);
        label_10->setObjectName(QStringLiteral("label_10"));
        label_10->setGeometry(QRect(500, 330, 56, 56));
        label_10->setFrameShape(QFrame::Box);
        label_10->setFrameShadow(QFrame::Plain);
        label_10->setScaledContents(false);
        label_11 = new QLabel(centralWidget);
        label_11->setObjectName(QStringLiteral("label_11"));
        label_11->setGeometry(QRect(320, 390, 51, 22));
        label_11->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignVCenter);
        lineEdit_13 = new QLineEdit(centralWidget);
        lineEdit_13->setObjectName(QStringLiteral("lineEdit_13"));
        lineEdit_13->setGeometry(QRect(210, 390, 91, 20));
        lineEdit_13->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_13->setReadOnly(true);
        max_weight_nn_7 = new QLabel(centralWidget);
        max_weight_nn_7->setObjectName(QStringLiteral("max_weight_nn_7"));
        max_weight_nn_7->setGeometry(QRect(400, 330, 47, 16));
        lineEdit_14 = new QLineEdit(centralWidget);
        lineEdit_14->setObjectName(QStringLiteral("lineEdit_14"));
        lineEdit_14->setGeometry(QRect(210, 350, 91, 20));
        lineEdit_14->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        lineEdit_14->setReadOnly(true);
        max_weight_nn_8 = new QLabel(centralWidget);
        max_weight_nn_8->setObjectName(QStringLiteral("max_weight_nn_8"));
        max_weight_nn_8->setGeometry(QRect(210, 330, 47, 16));
        pushButton = new QPushButton(centralWidget);
        pushButton->setObjectName(QStringLiteral("pushButton"));
        pushButton->setGeometry(QRect(100, 240, 75, 23));
        QPalette palette;
        QBrush brush(QColor(85, 255, 127, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::Button, brush);
        palette.setBrush(QPalette::Inactive, QPalette::Button, brush);
        palette.setBrush(QPalette::Disabled, QPalette::Button, brush);
        pushButton->setPalette(palette);
        pushButton->setCheckable(false);
        spinBox_3 = new QSpinBox(centralWidget);
        spinBox_3->setObjectName(QStringLiteral("spinBox_3"));
        spinBox_3->setGeometry(QRect(100, 210, 81, 22));
        spinBox_3->setMaximum(99999999);
        textEdit = new QTextEdit(centralWidget);
        textEdit->setObjectName(QStringLiteral("textEdit"));
        textEdit->setGeometry(QRect(580, 20, 121, 421));
        QFont font1;
        font1.setPointSize(8);
        textEdit->setFont(font1);
        label_12 = new QLabel(centralWidget);
        label_12->setObjectName(QStringLiteral("label_12"));
        label_12->setGeometry(QRect(60, 361, 51, 20));
        QFont font2;
        font2.setPointSize(12);
        font2.setBold(true);
        font2.setWeight(75);
        label_12->setFont(font2);
        lineEdit_15 = new QLineEdit(centralWidget);
        lineEdit_15->setObjectName(QStringLiteral("lineEdit_15"));
        lineEdit_15->setGeometry(QRect(120, 359, 51, 21));
        lineEdit_15->setFont(font2);
        label_13 = new QLabel(centralWidget);
        label_13->setObjectName(QStringLiteral("label_13"));
        label_13->setGeometry(QRect(60, 210, 41, 20));
        spinBox_6 = new QSpinBox(centralWidget);
        spinBox_6->setObjectName(QStringLiteral("spinBox_6"));
        spinBox_6->setGeometry(QRect(100, 150, 81, 22));
        spinBox_6->setMaximum(99999999);
        spinBox_6->setValue(100);
        label_14 = new QLabel(centralWidget);
        label_14->setObjectName(QStringLiteral("label_14"));
        label_14->setGeometry(QRect(30, 150, 71, 20));
        label_15 = new QLabel(centralWidget);
        label_15->setObjectName(QStringLiteral("label_15"));
        label_15->setGeometry(QRect(20, 180, 71, 20));
        doubleSpinBox = new QDoubleSpinBox(centralWidget);
        doubleSpinBox->setObjectName(QStringLiteral("doubleSpinBox"));
        doubleSpinBox->setGeometry(QRect(101, 180, 81, 22));
        doubleSpinBox->setSingleStep(0.01);
        doubleSpinBox->setValue(0.1);
        pushButton_2 = new QPushButton(centralWidget);
        pushButton_2->setObjectName(QStringLiteral("pushButton_2"));
        pushButton_2->setGeometry(QRect(100, 310, 75, 23));
        doubleSpinBox_2 = new QDoubleSpinBox(centralWidget);
        doubleSpinBox_2->setObjectName(QStringLiteral("doubleSpinBox_2"));
        doubleSpinBox_2->setGeometry(QRect(120, 280, 61, 22));
        doubleSpinBox_2->setDecimals(4);
        doubleSpinBox_2->setMaximum(1);
        doubleSpinBox_2->setSingleStep(0.0001);
        doubleSpinBox_2->setValue(0.01);
        label_16 = new QLabel(centralWidget);
        label_16->setObjectName(QStringLiteral("label_16"));
        label_16->setGeometry(QRect(10, 270, 101, 41));
        label_16->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_17 = new QLabel(centralWidget);
        label_17->setObjectName(QStringLiteral("label_17"));
        label_17->setGeometry(QRect(20, 450, 681, 131));
        label_17->setFrameShape(QFrame::Box);
        label_17->setFrameShadow(QFrame::Plain);
        label_18 = new QLabel(centralWidget);
        label_18->setObjectName(QStringLiteral("label_18"));
        label_18->setGeometry(QRect(20, 390, 51, 21));
        label_18->setFont(font2);
        lineEdit_16 = new QLineEdit(centralWidget);
        lineEdit_16->setObjectName(QStringLiteral("lineEdit_16"));
        lineEdit_16->setGeometry(QRect(80, 389, 91, 21));
        lineEdit_16->setFont(font2);
        lineEdit_16->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        MainWindow->setCentralWidget(centralWidget);
        groupBox_7->raise();
        groupBox_5->raise();
        groupBox_4->raise();
        groupBox_6->raise();
        groupBox->raise();
        groupBox_2->raise();
        label->raise();
        spinBox->raise();
        spinBox_2->raise();
        label_3->raise();
        label_4->raise();
        max_weight_nn->raise();
        min_weight_nn->raise();
        lineEdit->raise();
        lineEdit_2->raise();
        lineEdit_3->raise();
        lineEdit_4->raise();
        max_weight_nn_2->raise();
        min_weight_nn_2->raise();
        groupBox_3->raise();
        lineEdit_5->raise();
        label_5->raise();
        max_weight_nn_3->raise();
        min_weight_nn_3->raise();
        lineEdit_6->raise();
        lineEdit_7->raise();
        min_weight_nn_4->raise();
        lineEdit_8->raise();
        label_6->raise();
        label_7->raise();
        max_weight_nn_5->raise();
        spinBox_4->raise();
        lineEdit_10->raise();
        max_weight_nn_6->raise();
        label_9->raise();
        lineEdit_12->raise();
        min_weight_nn_6->raise();
        min_weight_nn_7->raise();
        label_8->raise();
        lineEdit_11->raise();
        lineEdit_9->raise();
        spinBox_5->raise();
        min_weight_nn_5->raise();
        label_10->raise();
        label_11->raise();
        lineEdit_13->raise();
        max_weight_nn_7->raise();
        lineEdit_14->raise();
        max_weight_nn_8->raise();
        pushButton->raise();
        spinBox_3->raise();
        textEdit->raise();
        label_12->raise();
        lineEdit_15->raise();
        label_13->raise();
        spinBox_6->raise();
        label_14->raise();
        label_15->raise();
        doubleSpinBox->raise();
        pushButton_2->raise();
        doubleSpinBox_2->raise();
        label_16->raise();
        label_17->raise();
        label_18->raise();
        lineEdit_16->raise();
        menuBar = new QMenuBar(MainWindow);
        menuBar->setObjectName(QStringLiteral("menuBar"));
        menuBar->setGeometry(QRect(0, 0, 721, 21));
        menuFile = new QMenu(menuBar);
        menuFile->setObjectName(QStringLiteral("menuFile"));
        MainWindow->setMenuBar(menuBar);
        mainToolBar = new QToolBar(MainWindow);
        mainToolBar->setObjectName(QStringLiteral("mainToolBar"));
        MainWindow->addToolBar(Qt::TopToolBarArea, mainToolBar);
        statusBar = new QStatusBar(MainWindow);
        statusBar->setObjectName(QStringLiteral("statusBar"));
        MainWindow->setStatusBar(statusBar);
        QWidget::setTabOrder(spinBox, spinBox_6);
        QWidget::setTabOrder(spinBox_6, doubleSpinBox);
        QWidget::setTabOrder(doubleSpinBox, spinBox_3);
        QWidget::setTabOrder(spinBox_3, doubleSpinBox_2);
        QWidget::setTabOrder(doubleSpinBox_2, pushButton);
        QWidget::setTabOrder(pushButton, pushButton_2);
        QWidget::setTabOrder(pushButton_2, lineEdit_4);
        QWidget::setTabOrder(lineEdit_4, lineEdit_3);
        QWidget::setTabOrder(lineEdit_3, lineEdit);
        QWidget::setTabOrder(lineEdit, lineEdit_2);
        QWidget::setTabOrder(lineEdit_2, lineEdit_5);
        QWidget::setTabOrder(lineEdit_5, lineEdit_6);
        QWidget::setTabOrder(lineEdit_6, lineEdit_12);
        QWidget::setTabOrder(lineEdit_12, lineEdit_8);
        QWidget::setTabOrder(lineEdit_8, lineEdit_10);
        QWidget::setTabOrder(lineEdit_10, lineEdit_7);
        QWidget::setTabOrder(lineEdit_7, lineEdit_14);
        QWidget::setTabOrder(lineEdit_14, lineEdit_13);
        QWidget::setTabOrder(lineEdit_13, lineEdit_11);
        QWidget::setTabOrder(lineEdit_11, lineEdit_9);
        QWidget::setTabOrder(lineEdit_9, spinBox_2);
        QWidget::setTabOrder(spinBox_2, spinBox_4);
        QWidget::setTabOrder(spinBox_4, spinBox_5);
        QWidget::setTabOrder(spinBox_5, lineEdit_15);
        QWidget::setTabOrder(lineEdit_15, lineEdit_16);
        QWidget::setTabOrder(lineEdit_16, textEdit);

        menuBar->addAction(menuFile->menuAction());
        menuFile->addAction(actionLoad_traning_sample);
        menuFile->addAction(actionLoad_test_sample);
        menuFile->addSeparator();
        menuFile->addAction(actionSave_network_configuration);
        menuFile->addAction(actionLoad_network_configuration);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "NNTraning", 0));
        actionLoad_traning_sample->setText(QApplication::translate("MainWindow", "Load traning sample", 0));
        actionLoad_test_sample->setText(QApplication::translate("MainWindow", "Load test sample", 0));
        actionSave_network_configuration->setText(QApplication::translate("MainWindow", "Save network configuration", 0));
        actionLoad_network_configuration->setText(QApplication::translate("MainWindow", "Load network configuration", 0));
        label->setText(QString());
        label_3->setText(QString());
        label_4->setText(QApplication::translate("MainWindow", "Unit num:", 0));
        max_weight_nn->setText(QApplication::translate("MainWindow", "max:", 0));
        min_weight_nn->setText(QApplication::translate("MainWindow", "min:", 0));
        max_weight_nn_2->setText(QApplication::translate("MainWindow", "max:", 0));
        min_weight_nn_2->setText(QApplication::translate("MainWindow", "min:", 0));
        groupBox->setTitle(QApplication::translate("MainWindow", "Input image", 0));
        label_2->setText(QApplication::translate("MainWindow", "Sample num:", 0));
        groupBox_2->setTitle(QApplication::translate("MainWindow", "Weight layer1", 0));
        groupBox_3->setTitle(QApplication::translate("MainWindow", "Output layer1", 0));
        label_5->setText(QString());
        max_weight_nn_3->setText(QApplication::translate("MainWindow", "max:", 0));
        min_weight_nn_3->setText(QApplication::translate("MainWindow", "min:", 0));
        groupBox_4->setTitle(QApplication::translate("MainWindow", "Output layer2", 0));
        min_weight_nn_4->setText(QApplication::translate("MainWindow", "min:", 0));
        label_6->setText(QString());
        label_7->setText(QApplication::translate("MainWindow", "Unit num:", 0));
        max_weight_nn_5->setText(QApplication::translate("MainWindow", "max:", 0));
        groupBox_6->setTitle(QApplication::translate("MainWindow", "Weight layer2", 0));
        max_weight_nn_6->setText(QApplication::translate("MainWindow", "max:", 0));
        label_9->setText(QString());
        min_weight_nn_6->setText(QApplication::translate("MainWindow", "min:", 0));
        min_weight_nn_7->setText(QApplication::translate("MainWindow", "min:", 0));
        label_8->setText(QString());
        groupBox_7->setTitle(QApplication::translate("MainWindow", "Weight layer3", 0));
        groupBox_5->setTitle(QApplication::translate("MainWindow", "Output layer3", 0));
        min_weight_nn_5->setText(QApplication::translate("MainWindow", "min:", 0));
        label_10->setText(QString());
        label_11->setText(QApplication::translate("MainWindow", "Unit num:", 0));
        max_weight_nn_7->setText(QApplication::translate("MainWindow", "max:", 0));
        max_weight_nn_8->setText(QApplication::translate("MainWindow", "max:", 0));
        pushButton->setText(QApplication::translate("MainWindow", "TUNE", 0));
        label_12->setText(QApplication::translate("MainWindow", "result:", 0));
        label_13->setText(QApplication::translate("MainWindow", "epoch:", 0));
        spinBox_6->setSpecialValueText(QString());
        spinBox_6->setSuffix(QString());
        label_14->setText(QApplication::translate("MainWindow", "refresh rate:", 0));
        label_15->setText(QApplication::translate("MainWindow", "speed training:", 0));
        pushButton_2->setText(QApplication::translate("MainWindow", "STOP", 0));
        label_16->setText(QApplication::translate("MainWindow", "stop when an error\n"
" of less than:", 0));
        label_17->setText(QString());
        label_18->setText(QApplication::translate("MainWindow", "RMSE:", 0));
        menuFile->setTitle(QApplication::translate("MainWindow", "File", 0));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
